### ISSUE TITLE
Postgres: permission denied for schema public

### ISSUE THREAD

**Issue by JonasHiltl** [pellepelster/solidblocks#40]
I'm using the solidblocks-rds-postgresql docker image in a docker-compose setup with two databases. The setup works well and the databases and users both get created. 
But when I connect to the database: `keycloak` with user: `keycloak` and password: `password` and try to create a table, e.g.
```sql
CREATE TABLE test (
	
);
```
I get the error 
```
ERROR:  permission denied for schema public
```
  
  Here is my docker compose to reproduce:
  ```yml
  rds:
    image: ghcr.io/pellepelster/solidblocks-rds-postgresql:15-v0.2.5
    container_name: rds
    volumes:
      - ./data:/storage/data
      - ./backup:/storage/backup
    ports:
      - 5432:5432
    environment:
      DB_INSTANCE_NAME: ocl
      DB_BACKUP_LOCAL: 1
      DB_ADMIN_PASSWORD: password
      DB_DATABASE_db1: keycloak
      DB_USERNAME_db1: keycloak
      DB_PASSWORD_db1: password
      DB_DATABASE_db2: app
      DB_USERNAME_db2: app_user
      DB_PASSWORD_db2: password
 ```
 
 I saw in the repo that this statements is executed to give permissions in the public schema:
```sh
psql_execute "${database}" "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO \"${username}\""
```
but found out that the statement only gives permissions for  **already existing** tables. So the user doesn't have permissions to create new tables in the public schema.
This [stackoverflow answer](https://dba.stackexchange.com/a/33960) explains how to give permissions for future tables.

I assume this behaviour isn't expected and the above statement should be adjusted to also grant default privileges for future tables.
