### ISSUE TITLE
Database data directory permissions

### ISSUE THREAD

**Issue by dominikzalewski** [pellepelster/solidblocks#49]
As explained in the documentation:

| configuration | type | description |
| ------------- | ----- | ------------|
| /some/data/dir:/storage/data | mount | Container volume mount for the PostgreSQL data directory. The docker image uses a user with uid 10000, which needs to be reflected in the directory permissions |

it is the responsibility of the 'user' to setup the docker environment so that the permissions to the mapped data directory from docker as setup to user 10000. However, as explained here https://github.com/docker/compose/issues/3270 named volumes are always created as root. We are using a docker compose with the following:

```
version: '3.9'

services:
  db:
    image: ghcr.io/pellepelster/solidblocks-rds-postgresql:17-snapshot-rc
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
      - pgdata:/storage/data
    env_file: "db.env"

volumes:
  pgdata:
```

We are thinking about implementing a workaround for this issue like explained here: https://pratikpc.medium.com/use-docker-compose-named-volumes-as-non-root-within-your-containers-1911eb30f731
which is basically to start a different docker container before postgres is started and have that additional container fix the permissions.

I do believe there is also another approach, where in the `Dockerfile` solidblocks could fix the permissions before the user is switched with:
```
USER ${USER}
```
ie. `chown -R 10000:10000 ${DATA_DIR}` would be executed.

Can you let us know whether that approach with changing the `Dockerfile` is likely to be implemented by solidblocks in near future? We would then know whether we need to implement the docker compose workaround or not.

**Comment by pellepelster** [comment]
I don't think the `Dockerfile` variant would work, since the code is executed at build time, and the volumes/directories are only attached at runtime, when the `Dockerfile` already was executed. The init container idea though is a good plan, I will look into that.

**Comment by dominikzalewski** [comment]
I see that you already have the idea from this article: https://pratikpc.medium.com/use-docker-compose-named-volumes-as-non-root-within-your-containers-1911eb30f731
included in the source code here: https://github.com/pellepelster/solidblocks/blob/main/solidblocks-rds-postgresql/contrib/docker-compose.yml

I've spent some time discovering this. I believe, if I had a reference to that docker-compose snippet, or to the article in the documentation where you write about volume mapping, that would save me a ton.

I agree that there is no way to make that work through `Dockerfile`. Thanks for explaining.

> The init container idea though is a good plan, I will look into that.
Not sure what you mean by that.

**Comment by dominikzalewski** [comment]
Turns out that docker swarm does not support `depends_on`: https://github.com/docker/compose/issues/9957#issuecomment-1329726003

However, I was able to remove the stanza safely, since the container for db does retry when it does not have write permission to the data directory, so in some way it will wait for the other container to fix permissions.

**Comment by dominikzalewski** [comment]
One more detail. The solution presented here

https://github.com/pellepelster/solidblocks/blob/main/solidblocks-rds-postgresql/contrib/docker-compose.yml

has the drawback that if you run it through docker swarm it keeps restarting the 'change-vol-ownership' service forever. I needed to modify this and add a policy to disable restarts:
```
services:
  change-vol-ownership:
    image: ubuntu
    user: "root"
    deploy:
      restart_policy:
        condition: none
    volumes:
      - db_data:/storage/data
      - db_backup:/storage/backup
    command: chown -R 10000:10000 /storage
``` 
I'm OK to close the issue.
